--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ElementalMinecraftGaming/TwitterMC
build-by-default: true
branches:
- main
projects:
  TwitterMC:
    path: ""
    libs:
       - src: jojoe77777/FormAPI
         version: ^2.0.0
...
